### PR TITLE
Add: Tourney client signatures

### PR DESCRIPTION
**Pull request by omkelderman**
Adds signatures for tourney client specific things. With it you can query the following data:
* IPC state (IPC cuz its also used by lazer tourney client, and its being written in ipc-state.txt), just decided to call it like that cuz thats how its probably known by the few ppl that know it exists :P
* Star counts for left and right team
* The BO
* whether or not Warmup is on
* whether or not chat is visible

### CODE REVIEW

**Comment by omkelderman** [comment]
fucked up some git commands lol (and only found out a while later oops) so had to force push a couple times, but should be gud now xd

**Comment by omkelderman** [comment]
welp, I was quite confident in this, but some time later, on another pc, it broke down....

Not super surprising considering the super large number in
https://github.com/Piotrekol/ProcessMemoryDataFinder/blob/34ca0d4c0118fabb1f897fee2c947780b5ff9f88/OsuMemoryDataProvider/OsuMemoryReader.cs#L155

This specific time if I changed that -2960 to 1808 (yes, no minus xD) then it works again. So ye, thats a jump of like almost 5k, big oof.

Its at least very clear now that that offset is not stable at all. I guess its time to find a pattern of its own for the TourneyBase signature, instead of offsetting it from OsuBase, since that clearly doesnt work....

**Comment by omkelderman** [comment]
tourney client things are now based of its own pattern instead of some super crazy offset from OsuBase, lets hope this stays alive.

Lets keep this PR in WIP status for a while to verify this stays alive after a couple osu updates or whatever

**Comment by omkelderman** [comment]
pattern worked on my pc and my laptop but didnt work on blacksharks pc so pattern is not stable, still needs better pattern :(

**Comment by omkelderman** [comment]
pattern seems to work, lets wait a while to see if updates break it 😄

**Comment by omkelderman** [comment]
still works with both stable and cuttingedge

**Comment by omkelderman** [comment]
as discussed on discord, also added a few things to the Tester UI for easier testing stuff, gives feedback about how long the reading takes, and you can selectively enable/disable some of the search patterns to figure out which take the most time if something is hanging or whatever

**Comment by omkelderman** [comment]
oh ye and uh with all this stuff on top from master branch etc, everything still works, so I'd say this is merge ready 👌

**Comment by Piotrekol** [comment]
re-tested again after some time has passed(osu updated once or twice) - still works as expected

**Pull request merged**
